### ISSUE TITLE
Migrating in Batches

### ISSUE THREAD

**Issue by anideswandikarMSFT** [rukmani-msft/adlsgen1togen2migrationsamples#45]
If customers wish to do the migration in multiple batches of applications, will the GitHub sample still be applicable? Or will we need to change some parameters. My hunch is that only the source and target folder paths will be changed based on the batches. But just wanted to confirm.

**Comment by chjayashree25** [comment]
Yes the migration will happen from the source path in Gen1 to destination path in Gen2. Parallelism can be achieved by giving multiple pipeline / activities in form of different source and destination paths as batches.
So the sample code will work here.
Thanks
