### ISSUE TITLE
Club small files into batches

### ISSUE THREAD

**Issue by anideswandikarMSFT** [rukmani-msft/adlsgen1togen2migrationsamples#46]
While migrating a large ADLS Backup, we observed that too many small files were taking longer to get migrated. Is there a way to club multiple small files into a migration batch and migrate them in larger batches to make the migration faster.

**Comment by chjayashree25** [comment]
Thanks for reaching out and raising this. Probably you can zip such files and post migration unzip.

**Comment by chjayashree25** [comment]
The 2 options:
Increase DIU and parallel copies, increase ingress limit at Gen2
Zip, migrate and unzip at Gen2

**Comment by anideswandikarMSFT** [comment]
Thanks. The zip/unzip idea might work. Let me suggest to them.
