### ISSUE TITLE
External Tables in SQL DW pointing to Data Lake

### ISSUE THREAD

**Issue by anideswandikarMSFT** [rukmani-msft/adlsgen1togen2migrationsamples#47]
My customer has a large number of External Tables in their SQL DW pointing to the Data Lake Gen1. While Migrating to Gen2, just changing the "Create External Data Source..." statement and pointing it to ADLS Gen2 is enough? Is any other change required. What has been the experience around Polybase External Tables for other customers who have migrated?

**Comment by chjayashree25** [comment]
Thanks for dropping the query here. We will get back to you on this.

**Comment by chjayashree25** [comment]
Hello,
Option1:  Change the end point to ADLS Gen2 in existing code.
Option2: Use of COPY command to directly load data from external location  to sql DW, which is similar feature of polybase. ( It reduces intermittent blob storage and directly copy data from ADLS Gen2 storage.

Reference: https://docs.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-load-from-azure-data-lake-store

Thanks,
Jayashree
