### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by anideswandikarMSFT** [rukmani-msft/adlsgen1togen2migrationsamples#48]
The Prerequisite section states that:
Service Principal need to have read, write and execute permission to resource group, key vault, data lake store Gen1 and data lake store Gen2. To learn more, see create service principal account and to provide SPN access to Gen1 refer to SPN access to Gen1.

Need to add ADF to the list of services that need SP Access. Without this, the scripts fail.

**Comment by chjayashree25** [comment]
As the ADF is created dynamically , the config file where in we providing the subscription details is having the SPN access and also on the resource group. This takes care for dynamic ADF factory
